version: "3.5"

services:
  spider:
    build: .
    image: clscraper
    depends_on:
      - pgdb
    env_file: .env
    volumes:
      - .:/app

  pgdb:
    image: postgres:12.3
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file: .env

  testdb:
    image: postgres:12.3
    env_file: .env

volumes:
  postgresdata: