"""Adding listing_type to postings

Revision ID: 9d379bd809fa
Revises: 87de71357a4b
Create Date: 2020-06-29 04:19:25.112390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d379bd809fa'
down_revision = '87de71357a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting_revisions', sa.Column('listing_type', sa.String(length=50), nullable=True))
    op.add_column('postings', sa.Column('listing_type', sa.String(length=50), nullable=True))
    op.execute("update postings set listing_type = 'apa'")
    op.execute("update posting_revisions set listing_type = 'apa'")
    op.alter_column('posting_revisions', sa.Column('listing_type', sa.String(length=50), nullable=False))
    op.alter_column('postings', sa.Column('listing_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postings', 'listing_type')
    op.drop_column('posting_revisions', 'listing_type')
    # ### end Alembic commands ###
