"""Add datetime expires

Revision ID: 87de71357a4b
Revises: b2780bd6fbe3
Create Date: 2020-06-25 08:04:20.616161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87de71357a4b'
down_revision = 'b2780bd6fbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting_revisions', sa.Column('datetime_post_expires', sa.DateTime(), nullable=True))
    op.add_column('postings', sa.Column('datetime_post_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postings', 'datetime_post_expires')
    op.drop_column('posting_revisions', 'datetime_post_expires')
    # ### end Alembic commands ###
