"""Title can be null if the posting is removed

Revision ID: b2780bd6fbe3
Revises: bc0653c02167
Create Date: 2020-06-25 07:52:52.767128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2780bd6fbe3'
down_revision = 'bc0653c02167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting_revisions', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting_revisions', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
